name: restaurants-api-cd

on:
  push:
    branches: 
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 8.0.x # specifying the dotnet version to be built
          
      - name: restore dependencies
        run: dotnet restore Restaurant/Restaurant.sln
        
      - name: build
        run: dotnet build Restaurant/Restaurant.sln --no-restore -c Release # skipping restoring because in the previous step i already restored dependencies
        
      - name: publish
        run: dotnet publish ./Restaurant/Restaurant.csproj --no-build -o ${{env.DOTNET_ROOT}}/api 
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with: 
            # Artifact name
            name: api-artifact
            # A file, directory or wildcard pattern that describes what to upload
            path: ${{env.DOTNET_ROOT}}/api
            
  deploy-to-dev:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v5.0.0
          with:
            # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
            name: api-artifact
        - name: Azure WebApp
          uses: Azure/webapps-deploy@v2.2.17
          with:
            # Name of the Azure Web App
            app-name: 'restaurants-api'
            # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
            publish-profile: ${{secrets.PUBLISH_PROFILE_DEV}}

  deploy-to-prod:
      runs-on: ubuntu-latest
      needs: deploy-to-dev
      steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v5.0.0
          with:
            # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
            name: api-artifact
        - name: Azure WebApp
          uses: Azure/webapps-deploy@v2.2.17
          with:
            # Name of the Azure Web App
            app-name: 'restaurants-api-production'
            # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
            publish-profile: ${{secrets.PUBLISH_PROFILE_PROD}}
    
    
